version: "3.8"

services:

  mysql:
    image: lcdhad141/ugr_had_141_mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    #volumes:
    #- ./mysqldb:/var/lib/mysql 
    environment:
    - MYSQL_ROOT_PASSWORD=${PASSWORD}
    - MYSQL_USER=${USERNAME}
    - MYSQL_PASSWORD=${PASSWORD}
    - MYSQL_DATABASE=${DATABASE}
    ports: 
      - "${PORT_MYSQL}:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${PASSWORD}
    - MYSQL_USER=${USERNAME}
    - MYSQL_PASSWORD=${PASSWORD}
    - MYSQL_DATABASE=${DATABASE}
    - PMA_ARBITRARY=1
    depends_on:
    - mysql
    ports: 
    - ${PORT_MYSQL_ADMIN}:80

  mongo:
    image: lcdhad141/ugr_had_141_mongodb:latest
    restart: always
    #volumes:
    #- ./mongodb:/data/db 
    environment:
    - ONGO_INITDB_ROOT_USERNAME=${USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    - MONGO_INITDB_DATABASE=${DATABASE}
    ports:
    - ${PORT_MONGO}:27017

  mongo-express:
    image: mongo-express:latest
      #image: mongo-express:1.0.0.alpha # es la latest
      #image: mongo-express:0.5.4 # no funciona
    restart: always
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${USERNAME}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    - ME_CONFIG_MONGODB_AUTH_USERNAME=${USERNAME}
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=${PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${PASSWORD}
    depends_on:
    - mongo
    ports:
    - ${PORT_MONGO_EXPRESS}:8081
